title: lexian.status
buildFuture: true
defaultContentLanguage: en
languageCode: en
baseURL: https://status.lexian.dev/
theme: cstate
preserveTaxonomyNames: true
taxonomies:
  affected: affected
outputs:
  page:
    - html
    - json
  section:
    - html
    - json
    - rss
  home:
    - html
    - json
    - rss
    - svg
  term:
    - html
    - json
    - rss
    - svg
outputFormats:
  svg:
    isPlainText: true
    mediaType: image/svg+xml
enableGitInfo: true
params:
  skipSeconds: true
  useRelativeTime: true
  disableDarkMode: false
  shortDateFormat: 15:04 UTC â€” Jan 2
  down: "#e60000"
  systems:
    - name: Lexian.DEV
      category: Lexian Services
    - name: timewisely.net
      category: TimeWisely Services
      description: A website by LexianDEV.
    - name: experiments.timewisely.net
      category: TimeWisely Services
  dateFormat: January 2, 2006 at 3:04 PM UTC
  brand: "#0a0c0f"
  enableLastMod: true
  headerTextColor: white
  logo: /img/logo.png
  incidentPostsPerPage: 9
  googleAnalytics: UA-00000000-1
  customTabs:
    - name: Login
      link: https://status.lexian.dev/admin/
  alwaysKeepBrandColor: true
  disableComplexCalculations: false
  useLogo: true
  disrupted: "#cc4400"
  notice: "#24478f"
  incidentHistoryFormat: monthly
  disableIncidentHistory: false
  ok: "#008000"
  categories:
    - name: Lexian Services
      description: Services
      closed: false
      untitled: true
    - closed: false
      untitled: true
      name: TimeWisely Services
      description: Services
  description: We continuously monitor the status of our services and if there are
    any interruptions, a note will be posted here.
  enableCustomHTML: true
  useLargeHeaderDesign: true
